### PR TITLE
Git shrinkwrap

### PR DESCRIPTION
**Pull request by lambdatastic**
This PR adds in the shrinkwrap stuff that @racerpeter was working on. We sat down and cherry picked the relevant code for it.

We pulled in #9 , so this should be merged in after it.

@lzrski , wanna review it?

/cc @jrolfs

### CODE REVIEW

**Comment by tad-lispy** [comment]
Thanks @lambdatastic. I'd love to take a look tomorrow or on the weekend.

Just a quick and raw though: maybe we can use different strategy to fix revisions. How about mimicking the behaviour of standard `npm` and having a command like this:

``` sh
npm-git install --save https://github.com/divdavem/octokat.js.git
```

to actually write to `package.json`'s `gitDependencies`, appending latest sha from `master`? The same for other branches, tags and obviously sha's e.g.:

``` sh
npm-git install --save https://github.com/divdavem/octokat.js.git#refactor
```

would write:

``` json
"gitDependencies": {
  "octokat.js": "https://github.com/divdavem/octokat.js.git#12a84b0"
}
```

as this is a `sha` of currently latest commit on this branch.

Does it make sense? Would it cover your use case for shrinkwrap?

**Comment by racerpeter** [comment]
Nice idea-- I think it would, yes.

**Comment by tad-lispy** [comment]
Could you please let me know what's your opinion on #11? It's an alternative solution to this PR. I'd like to move forward with this stuff in either direction - preferably this weekend. Your feedback would be of great value to me.

**Comment by lambdatastic** [comment]
I think that we might wanna close this and go with #11 for now. Eventually, we want to get everything working properly, but for now, pinning to SHAs seems to get done what we need.

@racerpeter , any thoughts?

**Comment by tad-lispy** [comment]
Closing this in favour of #11. Thanks for the inspiration :)

**Pull request closed without merging**
