### PR TITLE
Cross spawn to allow windows compatibility

### LINKED ISSUE #19: Spawn command doesn't work on windows
After `npm install`, my git repo gets pulled down and after switching to the correct branch it errors out with `Error: spawn npm ENOENT`.

`npm install` works fine for my project on Linux, but I think the issue on windows is related to:
https://github.com/nodejs/node-v0.x-archive/issues/2318

Perhaps change to https://www.npmjs.com/package/cross-spawn ?

### PR DESCRIPTION
**Pull request by mattvaughan**
Should close #19

### CODE REVIEW

**Comment by jdkrebs** [comment]
@m0v0nage @lzrski Has this been tested? It looks like this would fix the issue on windows. Thoughts? Can I help?

**Comment by tad-lispy** [comment]
Hello, @m0v0nage. Thanks for the PR and sorry for late reaction. It looks good to me, but I have not tested it myself. 

@jdkrebs - if you have Windows machine and can test if this works, than it would be a welcome help.

**Comment by jdkrebs** [comment]
@m0v0nage @lzrski I gave it a shot on a colleagues windows 10 machine and it seemed to work with the latest version of node/npm. Not sure if more testing would be needed or not but it would get a 👍 from me.

**Comment by mattvaughan** [comment]
I've tested it on previous versions of NPM on linux and windows. Works for me.

**Comment by MarekSalat** [comment]
any progress on this? I would like to use this on windows, but it is not possible right now

**Comment by tad-lispy** [comment]
Hey, everyone!

It is merged and published on [npmjs.org](https://www.npmjs.com/package/npm-git-install). Thank you for your participation and sorry for the delay.

**Comment by MarekSalat** [comment]
Hi thank you :) There is one small issue with this. maybe you can help me. I have package with this package.json
```
"scripts": {
    "prepublish": "npm run build",
    "build": "set WEBPACK_ENV=build && webpack",
  }
```
the package also has .gitignore with a record ignoring my `dist` folder. (I dont want to commint build files)

in my app I have `"install": "npm-git install"` and `gitDependencies: {...}`

there are two issues, the first problem is that the package build is called multiple times, but the other more serious problem is that my `dist` is never copied due the `.gitignore` file, if I remove the file the `dist` folder  is copied to my `node_modules`.

**Comment by tad-lispy** [comment]
Hi, Marek.

I don't think this is related to this PR - am I missing something? If not, then please open a new issue for that. Also please provide more context - is your package targeting a browser or node.js, provide some output, etc.

**Comment by MarekSalat** [comment]
My bad, you are right, sorry about that.

**Pull request merged**
